### ISSUE TITLE
Seaching is slow

### ISSUE THREAD

**Issue by gitletH** [the-rango/AntAlmanac#26]
It takes two seconds to get the search result back for searching for all CS classes. I noticed that the response time is directly proportional to the number of entries returns back.

![image](https://user-images.githubusercontent.com/18585305/52614018-1c10e080-2e45-11e9-820e-1668b0144a04.png)

**Comment by the-rango** [comment]
Search is slow mostly because we make sure to always return live data. 

Antplanner is faster because it caches the search results, but the downside to that is the data you get is outdated. I think he updates his cache once a day (? not sure, don't quote me on this). But in any case the numbers you see on AntAlmanac should be the same as what you see on webSOC.

In any case, we have a dope loading gif haha

@devsdevsdevs

**Comment by gitletH** [comment]
Have you considered defer loading live data? Like, return a cached but relatively fresh(like an hour) data immediately so that there's something on the screen that the users can see. Then retrieve the live data and update the page correspondingly.
Faster loading speed can improve user experiences a lot.

**Comment by the-rango** [comment]
Update: the team is talking about it; you got a really good point there!
Thank you so much for the suggestion!

**Comment by gitletH** [comment]
Glad that I can help!

**Comment by the-rango** [comment]
@gitletH I think it's funny how you've come back to work on this feature urself XD

**Comment by the-rango** [comment]
Closing this for now since we've pretty much explored everything in this thread.
But will always continue to improve search speed for a better ux. 
Thanks @gitletH
