### ISSUE TITLE
Looking for something better

### ISSUE THREAD

**Issue by gitletH** [the-rango/AntAlmanac#31]
This is an really amazing project in technical aspects. You guys solve many technical challenges that the AntPlanner was not able to solve. But from a user's persepctive, this app does not offer enough reasons why I should switch from the AntPlanner, which is what I am really familiar with, to the AntAlmanac.

One issue most of AntPlanner's predecessors have is that they look and function exactly the same as the old AntPlanner. There's a weekly calendar on the left half of the page, there's a place where you can search for classes on the right half. You can save or load a schedule using a unique ID. And you can add a class to the schedule by clicking on the class tile.

It's okay to borrow ideas from other apps. But AntPlanner is a crappy app, and that's why you guys are trying to build something that's better. AntPlanner is just an app that a random dude hacked together over a weekend. He didn't design this thing at all. He just grabbed a calendar from a library, put WebSoc into a `iframe`, then stuff them together in a single webpage. He didn't even bother to add a "Add" button, instead you just click on the class tile to add a class.

I like the material UI that you guys built. It looks really pleasant. And I like the features you guys added here and there. But there no appealing reasons why I would prefer AntAlmanc than AntPlanner. Both of them are the same, it just that one of them has a more modern GUI. I hope you guys can look into some other popular calendar apps outside of UCI, and build something better that the users can just ditch AntPlanner right away.

**Comment by the-rango** [comment]
Hey there gitletH, 

First I just want to thank you for your interest in the AntAlmanac and for suggesting fixes here and there! They have been very helpful and inspiring.

I sincerely appreciate your comments, and I must say I agree with many of the things you said here - antplanner really does not have the best UI.

When we first started, we did not want to completely reinvent the wheel, and we wanted to preserve some familiarity with antplanner since the UI was functional and most users were familiar with it. 

However as we added more features, we realized exactly what you pointed out here, that the UI really needs some drastic improvements. This is why this entire past quarter, we have been redesigning our app. Without breaking anything, we tried to improve our features here and there. So trust me that the redesign has been keeping us awake for the last couple of months. 

(Side note, we will be working with the Product Club later to be more professional and systematic in our design process).

We did do a bunch of research as you suggested on scheduling apps that other schools use and the conclusion we have come to is that there are not a whole lot of choices for the UI of a scheduling app. Most of these layouts fall on a continuum with antplanner's side by side design on one extreme and courseeater's tabs design on the other. 

We are trying to combine the two approach with a side-by-side design that also uses tabs (see our latest rendition in the tabs branch).

(TBH there is a lot of details here (some of which I am omitting), since we have been doing a lot of research and thinking like I said. And so I would love to talk you in person about these details (probably be easier too). Besides, I think you have some great ideas for the UI and I really want to hear more about them. Please do hit us up, and let's arrange a meeting!)

Now with that said, the biggest break-through that we hope to achieve is not in the UI itself, but in the way we approach software. Good software needs to be maintained. Google has a whole company working on a search engine they pretty much perfected 20 years ago. This is also the same thing we see with very successful course planning software in other schools: organizations (rather than individuals) working as a team to produce and maintain professionally designed software.

Very few people are talented enough to get it right the first time and write code that they never have to go back to. That's why to write good code you need to pass the torch. Antplanner falls behind because there is no one after Ryan to keep improving on his code. That's why we are building ourselves into an organization and recruiting new people so that we do not suffer from the same lack of foresight. 

So then yes, you are right, we do need to work on our UI/UX. And that is exactly what we are doing, thanks to our organization.

Now finally about the idea of attracting antplanner users. For one thing, we are hoping to build more than just a scheduler (which is everything antplanner is) into the AntAlmanac, with additional services like historical enrollment and notifications (and others; more to come later). 

For another, and I will be very frank here, we simply do not care enough about attracting antplanner users like you. I hope you don't take it the wrong way, but people who are currently very familiar with antplanner will be graduating soon. Because they are so comfortable with antplanner's design, many users are not used to the AntAlmanac. That is fine because we play for keeps. In the long run, users who are "switching from antplanner" will be a minority. 

In any case, sorry about the long reply (and the late reply). Again, there is a lot going on here that I would love to share with you and get your opinions on! 

Have a nice finals week and Spring Break!

**Comment by gitletH** [comment]
Sure. I will love to meet with you after the break. Should I send you an email or a FB message regarding the details?

**Comment by the-rango** [comment]
Sounds good. Emailing is fine :)

**Comment by gitletH** [comment]
email sent. Future conversation will be moved there
